### PR TITLE
Attempt error recovery from partial matches in separated lists

### PR DESCRIPTION
**Pull request by Xanewok**
Based on #593.

Implements a dedicated `SeparatedHelper` (no state, can change to a free function) that implements recovering from partial matches in separated lists.

There are 3 ways we can recover:
1. a separatee matches but unexpected tokens follow before a separator
2. a separatee is partially matched
3. a separatee can't be parsed

Ideally we should recover in all three cases, however because the the trailing separator is not mandatory (nor legal), cases 1. and 3. are tricky. In case 2  The separated-by lists are not always in a delimited group (e.g. `IdentifierPath`) and so there's no sure way to bound the recovery, as the unexpected tokens (i.e. not a separator) can be already part of the outer parse.

For instance, `0.0.0 || 0.0.0` (case 1) or `0.0. || 0.0.0` (case 3) might attempt to recover by skipping the ` || 0` part. Until we constrain the error recovery with a la FOLLOW for the recovering parser, we can't reliably recover errors for now in these cases.

### CODE REVIEW

**Comment by Xanewok** [comment]
@OmarTawfik looks like a spurious sccache failure:

```
 error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/runner/work/slang/slang/bin/sccache rustc - --crate-name ___ --print=file-names --warn unused_crate_dependencies --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 2)
  --- stderr
  sccache: error: Timed out waiting for server startup. Maybe the remote service is unreachable?
  Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information
  ```

**Comment by OmarTawfik** [comment]
> @OmarTawfik looks like a spurious sccache failure:

Looks like it recovered on retry. Please let me know if you see it again and I can look into it.

**Comment by Xanewok** [comment]
Updated and CI is green

**Review by AntonyBlakey — CHANGES_REQUESTED** [review]
I think in general that when testing for resynchronization we should prove the recovery. Currently our code samples don't show this because they don't have any following context.

**Comment by Xanewok** [comment]
I added a test with error recovery for the identifier path lists (so nested separated-by lists) in the function definition and in the individual expressions of the following body, which shows that we recover individually everywhere:


https://github.com/NomicFoundation/slang/pull/595/files#diff-6ac3c03a1f9a12cdb00f8a531141082f21c485d841f2001d778202385d5ab4d3
```solidity
function all() override(some.ident unexpected tokens, ISomeInterface, Other) public {
  msg.sender.call{do: 1, arg: 1 }();
  msg.sender.call{, empty: 1, parse: 2 }();
  msg.sender.call{arg: 1, missing_expr: , no_semicolon, , }();
  msg.sender.call{arg: 1 unexpected tokens, not: 2, recovered, yet: 3, }();

}

function empty() override(some.ident, /* empty */, other.arg.here, and.here);

function nested_lists() override(some.ident, next.do.that, other.while, next.one, final, ultimate);
function nested_lists() override(some., next.arg, next.one, ultimate);
```

Do you want me to also fill the bodies of these functions for completeness' sake and/or find a more complete example for the recovery implemented here?

**Comment by AntonyBlakey** [comment]
> Do you want me to also fill the bodies of these functions for completeness' sake and/or find a more complete example for the recovery implemented here?

No, I just wanted to show that we recovered and continued.

**Review by AntonyBlakey — APPROVED** [review]

**Comment by Xanewok** [comment]
Updated

**Pull request merged**
