### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fzeoli**
Give more visibility to the Telegram group link

### CODE REVIEW

**Review by AntonyBlakey — APPROVED** [review]

**Comment by OmarTawfik** [comment]
@fzeoli there are a few formatting issues, plus more `README` files to update/keep in sync.
I created #1069 with the updates, and fixed the ones here.
Please let me know if you have any suggestions.

**Comment by fzeoli** [comment]
Thanks! Not sure what the formatting issue is, I can't see one in my diff (and I edited using Github's online editor 😅). The quote block ("> ") I removed on purpose as it was giving the line a weaker visual hierarchy. Removing that was raising visibility a bit so it doesn't risk going unnoticed as a footer kinda thing.
The one I mainly care about is the one that's displayed on the repo page @NomicFoundation/slang -- the other ones I don't think matter as much as this one.

**Comment by OmarTawfik** [comment]
@fzeoli the same README message is displayed in:

1. [this repository:](https://github.com/NomicFoundation/slang/blob/main/README.md)

image

2. [the Rust crate:](https://crates.io/crates/slang_solidity)

image

3. [the NPM package:](https://www.npmjs.com/package/@nomicfoundation/slang)

image

Perhaps it is only "less" visible in the first case? what about we use a [GitHub (caution?) alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) instead of a `<blockquote>`? it will look like this:

> [!CAUTION]
> This project is still in alpha, and is under active development. If you are planning on using it, please [reach out to us on Telegram](https://t.me/+pxApdT-Ssn5hMTFh) so we can help you get started.

**Comment by fzeoli** [comment]
I still don't understand what the formatting issue is, but with the Telegram link having its own separate line in addition to being mentioned in the warning sentence, I think that mostly achieves my intent. 

As of right now I think the changes I originally suggested work, but feel free to modify it as you see fit as long as the link to the Telegram group is prominent, easy to find, and not communicated only in the context of a long grayed out sentence about the project being in alpha.

The caution formatting does make it stand out more, but it also makes it feel more alarming, which may deter people from using Slang, rather than letting them know that they should be careful

**Comment by OmarTawfik** [comment]
> I still don't understand what the formatting issue is 

The original formatting issue is [here](https://github.com/NomicFoundation/slang/actions/runs/10324024828/job/28582616797):

>  [warn] README.md
>  [warn] Code style issues found in the above file. Run Prettier with --write to fix.
>
>  Command failed with code '1' and signal 'UNKNOWN':
>  prettier --check .

Running that command line locally removes the trailing spaces on the last lines [here](https://github.com/NomicFoundation/slang/blob/9773e27654e58cf28d64840b8544802e1f5d7430/README.md?plain=1#L28C56-L28C57).

> the Telegram link having its own separate line in addition to being mentioned in the warning sentence, I think that mostly achieves my intent.

> The alpha warning isn't the main thing though. The Telegram group is.

Sounds good.

**Pull request closed without merging**
